export const USER_HAS_CHANGED = 'USER_HAS_CHANGED';
export const USER_POST_HAS_CHANGED = 'USER_POST_HAS_CHANGED';

export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'
export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'
export const CLEAR_DATA = 'CLEAR_DATA'